# Generated by Django 4.1.2 on 2022-11-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_items_item_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='items_reviews',
            new_name='item_reviews',
        ),
    ]
