# Generated by Django 4.1.2 on 2022-11-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_items_reviews_items_item_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={},
        ),
        migrations.AlterField(
            model_name='items',
            name='item_price',
            field=models.FloatField(default=0),
        ),
    ]
