# Generated by Django 4.1.2 on 2022-11-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_items_item_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
    ]
